FROM inwt/r-batch:latest

EXPOSE 3838

RUN installAutomake 1.16.1 \
    && installPackage \
    DT \
    htmlwidgets \
    leaflet \
    sf \
    shiny \
    shinyalert \
    shinybusy \
    shinydashboard \
    shinyjs \
    shinythemes \
    plotly
