FROM inwt/r-batch:4.1.3

EXPOSE 3838

RUN installAutomake 1.16.1 \
    && installPackage \
    DT \
    htmlwidgets \
    leaflet \
    sf \
    shiny \
    shinydashboard \
    shinyjs \
    shinythemes \
    plotly
