name: retrieve last_pushed_tag date

on:
  schedule:
    - cron: '0 3,9,15,21 * * *' # 4 times per day
  workflow_dispatch: # manually running a workflow

jobs:
  last_pushed-date:
    runs-on: ubuntu-latest

    env:
      RVERSION: '4.2.0'
    
    steps:
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq
    
    - name: extract ubuntu image
      id: ubuntu-image
      run: |
        u_img="$(curl -sSL https://raw.githubusercontent.com/rocker-org/rocker-versioned2/master/dockerfiles/r-ver_$RVERSION.Dockerfile \
        | grep "FROM" | cut -d ':' -f 2)"
        echo "::set-output name=u_img::$u_img"
    
    - name: extract rocker last_pushed_tag date
      id: rocker-date
      run: |
        rocker_date=$(curl -s https://hub.docker.com/v2/repositories/rocker/r-ver/tags/$RVERSION \
        | jq '.tag_last_pushed')
        echo "::set-output name=rocker_date::$rocker_date"

    - name: extract ubuntu last_pushed_tag date
      id: ubuntu-date
      run: |
        ubuntu_date=$(curl -s https://hub.docker.com/v2/repositories/library/ubuntu/tags/${{ steps.ubuntu-image.outputs.u_img }} \
        | jq '.tag_last_pushed')
        echo "::set-output name=ubuntu_date::$ubuntu_date"
    
    - name: Display Vars
      run: |
        echo "rocker/r-ver:$RVERSION" 
        echo "last_pushed_tag date: ${{ steps.rocker-date.outputs.rocker_date }}"
        echo "ubuntu:${{ steps.ubuntu-image.outputs.u_img }}"
        echo "last_pushed_tag date: ${{ steps.ubuntu-date.outputs.ubuntu_date }}"
