name: retrieve image build dates

on:
  schedule:
  #  - cron: '0 3,9,15,21 * * *' # 4 times per day
  workflow_dispatch: # manually running a workflow

jobs:
  last_pushed-date:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Get R Version from local dockerfile
      id: r-version
      run: |
        RVERSION=$(cat r-base/Dockerfile |  grep "FROM" | cut -d ':' -f 2)
        echo "RVERSION=$RVERSION" >> $GITHUB_ENV
    
    - name: extract ubuntu image
      id: ubuntu-image
      run: |
        U_IMG="$(curl -sSL \
        https://raw.githubusercontent.com/rocker-org/rocker-versioned2/master/dockerfiles/r-ver_${RVERSION}.Dockerfile \
        | grep "FROM" | cut -d ':' -f 2)"
        echo "U_IMG=$U_IMG" >> $GITHUB_ENV
    
    - name: extract rocker last_pushed_tag date
      id: rocker-date
      run: |
        rocker_date=$(curl -s \
        https://hub.docker.com/v2/repositories/rocker/r-ver/tags/${RVERSION} \
        | jq -r '.tag_last_pushed')
        echo "ROCKER_DATE=$rocker_date" >> $GITHUB_ENV

    - name: extract ubuntu last_pushed_tag date
      id: ubuntu-date
      run: |
        ubuntu_date=$(curl -s \
        https://hub.docker.com/v2/repositories/library/ubuntu/tags/${U_IMG} \
        | jq -r '.tag_last_pushed')
        echo "UBUNTU_DATE=$ubuntu_date" >> $GITHUB_ENV
    
    - name: Display Vars
      run: |
        echo "rocker/r-ver:$RVERSION"
        echo "ubuntu-img: $U_IMG"
        echo "last_pushed_tag Rocker date: $ROCKER_DATE"
        echo "last_pushed_tag Ubuntu date: $UBUNTU_DATE"

        # Convert dates to Unix timestamps
        rocker_date_sec=$(date --date="$ROCKER_DATE" +%s)
        ubuntu_date_sec=$(date --date="$UBUNTU_DATE" +%s)
        now_sec=$(date +%s)

        # Calculate difference
        diff=$((ubuntu_date_sec-rocker_date_sec))
        diff_rocker=$((now_sec-rocker_date_sec))
        diff_ubuntu=$((now_sec-ubuntu_date_sec))

        # Convert difference to human-readable format
        diff_date=$(date -u -d @"$diff" +'%j days %-Hh %-Mm %-Ss')
        diff_rocker_date=$(date -u -d @"$diff_rocker" +'%j days %-Hh %-Mm %-Ss')
        diff_ubuntu_date=$(date -u -d @"$diff_ubuntu" +'%j days  %-Hh %-Mm %-Ss')

        echo "Now is: $(date)"
        echo "Difference between build dates: $diff_date"
        echo "Difference between now and rocker build date: $diff_rocker_date"
        echo "Difference between now and ubuntu build date: $diff_ubuntu_date"
